version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: greenweez sales information
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: date of sales
          - name: orders_id
            description: identification of order
          - name: pdt_id
            description: identification of product
          - name: revenue
            description: turnover of sales
          - name: quantity
            description: number of product which sale
          
      - name: product
        identifier: raw_gz_product
        description: greenweez product information
        columns:
          - name: products_id
            description: identification of product
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: price of product
      - name: ship
        identifier: raw_gz_ship
        description: greenweez ship information
        columns:
          - name: orders_id
            description: identification of order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: cost of shipping for customer
          - name: logCost
            description: logistics cost
          - name: ship_cost
            description: cost of ship for company
      - name: adwords
        identifier: raw_gz_adwords
        description: information from adwords
        tests:
          - unique:
              columns_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: information from bing
        tests:
          - unique:
              columns_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: information from criteo
        tests:
          - unique:
              columns_name: "(date_date || '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: information from facebook
        tests:
          - unique:
              columns_name: "(date_date || '-' || campaign_key)"
              